# Generated by Django 6.1 on 2026-08-22 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روز')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام حرکت')),
                ('exercise_type', models.CharField(choices=[('weight', 'وزنه\u200cای'), ('time', 'زمانی (ثانیه)')], default='weight', max_length=10, verbose_name='نوع حرکت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='تاریخ هفته (میلادی - داخلی)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزنه (کیلوگرم)')),
                ('reps_set1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تکرار ست ۱')),
                ('reps_set2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تکرار ست ۲')),
                ('reps_set3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تکرار ست ۳')),
                ('reps_set4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تکرار ست ۴')),
                ('duration_set1', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت ست ۱ (ثانیه)')),
                ('duration_set2', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت ست ۲ (ثانیه)')),
                ('duration_set3', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت ست ۳ (ثانیه)')),
                ('duration_set4', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت ست ۴ (ثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start'],
                'unique_together': {('exercise', 'week_start')},
            },
        ),
    ]
